@extends('layouts.front.app')

@section('content')
    <div class="container">
        <div class="main py-4">
            <div class="row">
                <div class="col-12 col-xl-12">
                    <div class="col-12 px-0">
                        <div class="card border-0 shadow">
                            <div class="card-body">
                                <h1 class="fs-5 fw-bold mb-1">BLINDSIDEBETS</h1>
                                <h1 class="fs-5 fw-bold mb-1">Terms and Conditions</h1>
                                <p>BLINDSIDEBETS Web Site is provided by BLINDSIDEBETS, LLC, a Delaware limited liability company (“BLINDSIDEBETS”). By accessing and using the web site located at www.blindsidebets.com (the “Web Site”), you agree to be bound by the Terms of Use (hereinafter, the “Terms” or “Agreement”) in effect at the time of each such access or other use.  You also acknowledge that BLINDSIDEBETS may, from time to time, in its sole discretion and without notification to you, change these Terms. You should review the Terms each time you visit or use the Web Site. If you do not agree to these Terms, do not use the Web Site. As used in these Terms of Use, “we” includes BLINDSIDEBETS and each of its affiliates.</p>
                                <p>
                                    You agree to not use the Service to submit or link to any Content which is defamatory, abusive, hateful, threatening, spam or spam-like, likely to offend, contains adult or objectionable content, contains personal information of others, risks copyright infringement, encourages unlawful activity, or otherwise violates any laws. You are entirely responsible for the content of, and any harm resulting from, that Content or your conduct.
                                    We may remove or modify any Content submitted at any time, with or without cause, with or without notice.
                                </p>

                                <h3 class="mt-5">Information Services</h3>
                                <p>The Web Site is intended solely to provide information, materials and data concerning sports handicapping and handicapper verification (the “Information”), which Information includes statistical information, handicapper picks and analysis, handicapper records, data, verification and rankings.  </p>
                                <p class="mt-5"><b>You understand and agree that the Website and Information are provided “AS-IS” and that BLINDSIDEBETS assumes no responsibility in connection with your use of the Website or any Information. Furthermore, the Website and Information are provided for entertainment purposes only and not to violate any federal, state or local laws. BLINDSIDEBETS does not encourage illegal gambling. If you wish to use the Information for wagering, please use a legal outlet. BLINDSIDEBETS is not responsible for any losses you incur as a result of using this Information for wagering.</b></p>

                                <h3 class="mt-5">Click-Through Agreements</h3>
                                <p class="mt-5">Before using certain areas of the Web Site  (including the registration of your Account), you may be asked to indicate your acceptance of additional special terms and conditions by clicking a button marked ”I Accept,” “I Agree,” “Okay,” “I Consent” or other words or actions that similarly acknowledge your consent or acceptance of a Click-Through Agreement. To the extent there is a conflict between these Terms and any Click-Through Agreement, the Click-Through Agreement will govern.</p>

                                <h3 class="mt-5">Account Registration</h3>
                                <p class="mt-5">In order to access or use the certain portions of the Web Site , you may be required to register and create an account (“Account”) with BLINDSIDEBETS.  Information gathered through the registration process and any other information related to your Account will be subject to these Terms as well as to our Privacy Policy.  You represent and warrant that you are at least 18 years old and that all information provided by you when creating your Account is true, accurate and complete and that you will maintain, at all times, true, accurate and complete information related to your Account. Information related to your Account should be maintained by you in a confidential manner, as you are solely responsible for the usage of your Account by any third parties with respect to the Web Site. It is your responsibility to advise us if you are aware of any unauthorized access to your Account or if your Account information has been made available by you to third-parties in a manner that may result in unauthorized usage of the Account. In our sole and absolute discretion, we may terminate your Account for any reason (including for reasons related to unlawful or unauthorized usage) and we are under no obligation to retain a record of your Account or any data or information that you may have stored by means of the Account. In the event of any such termination, you will no longer have access to the Web Site . </p>

                                <h3 class="mt-5">Typographical Errors</h3>
                                <p class="mt-5">In the event any product or service is listed at an incorrect price or with incorrect information due to typographical error or error in pricing or related information, BLINDSIDEBETS shall have the right to refuse or cancel any orders placed for product listed at the incorrect price. BLINDSIDEBETS shall have the right to refuse or cancel any such orders whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is canceled, BLINDSIDEBETS shall immediately coordinate the issuance of a credit to your credit card account in the amount of the charge.</p>

                                <h3 class="mt-5">Order Acceptance Policy</h3>
                                <p class="mt-5">Your receipt of an electronic or other form of order confirmation does not signify our acceptance of your order, nor does it constitute confirmation of our offer to sell. BLINDSIDEBETS reserves the right at any time after receipt of your order to accept or decline your order for any reason. BLINDSIDEBETS reserves the right at any time after receipt of your order, without prior notice to you, to supply less than the quantity you ordered of any item. All orders placed must obtain pre-approval with an acceptable method of payment, as established by our credit card processor(s). We may require additional verifications or information before accepting any order.</p>

                                <h3 class="mt-5">Access to the Web Site</h3>
                                <p class="mt-5">No person under the age of eighteen (18) is authorized to access or use the Web Site .  User access to, and use of, the Web Site is subject to all applicable laws and regulations.  Use of the Web Site is void where prohibited.  By using the Web Site, you represent and warrant that you are eighteen (18) years of age and that you have the right, authority and capacity to enter into this Agreement and abide by the Terms.</p>
                                <p class="mt-5">Except as otherwise sanctioned pursuant to a valid Reseller License, BLINDSIDEBETS grants you a limited, non-transferable right of access and use the Web Site and Information for non-commercial purposes only. Such access shall enable you to use the Web Site and Information for informational purposes. This right of access shall not include any resale or commercial use of the Web Site or its contents, including any Information; any derivative use of the Web Site or its contents, including any Information; or any use of data mining, robots, or similar data gathering and extraction tools. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of BLINDSIDEBETS or our affiliates without our prior express written consent. For the avoidance of doubt, you may not distribute, modify, republish, or publicly display any of the Information without prior written permission of BLINDSIDEBETS.</p>
                                <p class="mt-5">We make no guarantees regarding the availability of the Web Site .  Furthermore, we reserve the right, within our sole discretion, to discontinue the Web Site. You agree that we will not be liable to you for any such discontinuance or modification of the Web Site.  Any rights not expressly granted by these Terms are reserved by us.</p>
                                <p class="mt-5">You are under no obligation to use or continue to use the Web Site and may temporarily or permanently cease using the Web Site without notice to BLINDSIDEBETS. Any use of the Web Site or any portion thereof, in violation of the foregoing shall constitute a violation of these Terms and may result in, among other things, termination or suspension of your rights to use the Web Site or any portion thereof.</p>

                                <h3 class="mt-5">Restrictions on Your Use</h3>
                                <p class="mt-5">All content within the Web Site, including the Information, and any materials made available for downloading, if any, are the property of BLINDSIDEBETS and/or its affiliates or other third parties.  The Web Site and portions of the Web Site is protected by copyright and trademark laws.  This Agreement does not grant any license to modify or alter the materials on the Web Site that are viewed, downloaded or otherwise accessed by you.  You shall keep intact all proprietary notices, including copyright notices, contained on any downloadable materials.  You shall be solely liable for any damages resulting from any infringement of copyright, trademark, or other proprietary right, or any and all harm resulting from your use of the Web Site. </p>
                                <p class="mt-5">To the extent applicable, when accessing the Web Site, you are required to use the security procedures currently or hereafter maintained by us to confirm that only authorized users have access to certain information provided at, or contained in, the Web Site.  You are prohibited from utilizing alter-egos or other disguised identities when accessing the Web Site. All forms of indirect and ‘spoofed’ access are strictly prohibited.</p>
                                <p class="mt-5">Do not submit, post or otherwise transmit via the Web Site information that is proprietary or confidential of third parties (whether by law or by contract) or that you otherwise do not have the legal right to use. Any information, content or other material, including, but not limited to, any feedback, data, answers, questions, comments, suggestions, plans, ideas, user reviews or the like, which you send to us will be treated as being non-confidential and non-proprietary. We assume no obligation to protect confidential or proprietary information (other than those outlined in our Privacy Policy) from disclosure.</p>

                                <h3 class="mt-5">Intellectual Property Ownership</h3>
                                <p class="mt-5">Any and all intellectual property rights associated with the Web Site, including, without limitation, any inventive concepts, know-how, publicity rights, trademarks, trade-dress, trade secrets, copyrights and patents (“Intellectual Property”) are the sole property of BLINDSIDEBETS or third parties. Except as otherwise expressly authorized by these Terms, you may not copy, reproduce, modify, lease, loan, sell, create derivative works from, upload, transmit, or distribute the Intellectual Property of the Web Site in any way without the express written consent of BLINDSIDEBETS or the express written consent of the appropriate third party, as applicable. Except as provided herein, BLINDSIDEBETS does not grant to you any express or implied rights to BLINDSIDEBETS or any third party’s Intellectual Property. </p>

                                <h3 class="mt-5">Privacy Policy</h3>
                                <p class="mt-5">Any personal information or other information about you collected by BLINDSIDEBETS through, or in connection with, the Web Site is subject to our Privacy Policy. BLINDSIDEBETS Privacy Policy is incorporated into the terms of this Agreement by this reference.  As indicated in these Terms, the Web Site is designed for adults of legal age (18 years and over). For questions about our online privacy policy please refer to the Privacy Policy.</p>

                                <h3 class="mt-5">Links</h3>
                                <p class="mt-5">The Web Site may provide or include links to other world wide web sites or resources. While BLINDSIDEBETS attempts to provide links only to third-party Web Sites that comply with all applicable laws and regulations and BLINDSIDEBETS’s standards, please understand that the content on these third-party Web Sites is subject to change without notice to BLINDSIDEBETS. Because we have no control over such sites and resources, you acknowledge and agree that BLINDSIDEBETS is not responsible for the availability of such external sites, or resources, and does not endorse and is not responsible or liable for any content, advertising, products or other materials on or available from such sites or resources. YOU FURTHER ACKNOWLEDGE AND AGREE THAT BLINDSIDEBETS SHALL NOT BE RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY DAMAGE OR LOSS CAUSED OR ALLEGED TO BE CAUSED BY OR IN CONNECTION WITH USE OF OR RELIANCE ON ANY SUCH CONTENT OR SITES AVAILABLE ON OR THROUGH ANY SUCH SITE OR RESOURCE.<br><br>BLINDSIDEBETS prohibits caching of any portion of the Web Site and any unauthorized hypertext links to the Web Site. We reserve the right to disable any unauthorized links or frames. If you desire to provide a hyperlink from your Web Site to the Web Site, you must contact BLINDSIDEBETS to discuss mutually agreeable terms for such hyperlink.  </p>

                                <h3 class="mt-5">Exclusion of Warranty</h3>
                                <p class="mt-5"><b>BLINDSIDEBETS MAKES NO WARRANTY OF ANY KIND REGARDING THE WEB SITE AND/OR ANY MATERIALS PROVIDED ON THE WEB SITE, ALL OF WHICH ARE PROVIDED ON AN “AS IS” “AS AVAILABLE” BASIS. BLINDSIDEBETS DOES NOT WARRANT THE ACCURACY, COMPLETENESS, CURRENCY OR RELIABILITY OF ANY OF THE CONTENT OR DATA FOUND ON THE WEB SITE, INCLUDING THE INFORMATION, AND EXPRESSLY DISCLAIMS ALL WARRANTIES, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, AND THOSE ARISING BY STATUTE OR OTHERWISE IN LAW OR FROM A COURSE OF DEALING OR USAGE OF TRADE. <br><br>BLINDSIDEBETS DOES NOT WARRANT THAT THE WEB SITE, ITS SERVERS OR ANY E-MAIL SENT FROM IT ARE SECURE, FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. <br><br>NEITHER BLINDSIDEBETS, NOR ITS AFFILIATES, MAKES ANY REPRESENTATIONS, WARRANTIES OR GUARANTEES REGARDING (1) THE OPERATION OR PERFORMANCE OF THE WEB SITE OR (2) THE INTERNET GENERALLY. <br><br>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. YOU MAY ALSO HAVE OTHER RIGHTS THAT VARY FROM JURISDICTION TO JURISDICTION AND THAT MAY NOT BE LIMITED BY THESE TERM, PROVIDED HOWEVER YOU AGREE AND ACKNOWLEDGE THAT TO THE EXTENT PERMISSIBLE UNDER APPLICABLE LAW, YOU WAIVE ANY SUCH STATUTORY RIGHTS WITH RESPECT TO IMPLIED WARRANTIES.</b></p>

                                <h3 class="mt-5">Limitation of Liability</h3>
                                <p class="mt-5"><b>BLINDSIDEBETS ASSUMES NO RESPONSIBILITY, AND SHALL NOT BE LIABLE FOR, ANY DAMAGES TO, OR VIRUSES THAT MAY INFECT YOUR COMPUTER EQUIPMENT OR OTHER PROPERTY ON ACCOUNT OF YOUR ACCESS TO, USE OF, OR BROWSING IN THE WEB SITE OR YOUR DOWNLOADING OF ANY MATERIALS, DATA, TEXT, IMAGES, VIDEO OR AUDIO FROM THE WEB SITE. IN NO EVENT SHALL BLINDSIDEBETS BE LIABLE FOR ANY INJURY, LOSS, CLAIM, DAMAGES, OR ANY SPECIAL, EXEMPLARY, PUNITIVE, DIRECT, INDIRECT, INCIDENTAL OR CONSEQUENTIAL DAMAGES OF ANY KIND (INCLUDING, BUT NOT LIMITED TO LOST PROFITS OR LOST SAVINGS), WHETHER BASED IN CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE, WHICH ARISES OUT OF OR IS IN ANY WAY CONNECTED WITH ANY USE OF THE WEB SITE OR CONTENT FOUND THEREIN.</b></p>

                                <h3 class="mt-5">Jurisdictional Issues</h3>
                                <p class="mt-5">Although the Web Site are accessible worldwide, not all information, products or services discussed or referenced herein are available to all persons or in all geographic locations. BLINDSIDEBETS makes no representation that materials on the Web Site are appropriate or available for use in other locations. Those who choose to access the Web Site from other locations do so on their own initiative and are responsible for compliance with local laws.</p>

                                <h3 class="mt-5">Choice of Law and Forum</h3>
                                <p class="mt-5">These Terms shall be governed by and construed in accordance with the laws of the State of Georgia, excluding its conflicts of law rules. You expressly agree that the exclusive jurisdiction for any claim or action arising out of or relating to these Terms shall be filed only in Atlanta, Georgia, and you further agree and submit to the exercise of personal jurisdiction of such courts for the purposes of litigating such claim or action.</p>

                                <h3 class="mt-5">Indemnity and Release</h3>
                                <p class="mt-5">By using the Web Site, you agree to indemnify BLINDSIDEBETS and its partners, officers, employees and agents and hold them harmless from any and all claims and expenses, including attorneys’ fees, arising from your use of the Web Site. By using the Web Site, you are hereby agreeing to release BLINDSIDEBETS and its partners, officers, employees and agents from any and all claims, demands, debts, obligations, damages (actual or consequential), costs and expenses of any kind or nature whatsoever, whether known or unknown, suspected or unsuspected, disclosed or undisclosed, that you may have against them arising out of or in any way related to your use of the Web Site.</p>

                                <h3 class="mt-5">Severability and Integration</h3>
                                <p class="mt-5">Unless otherwise specified herein, this Agreement constitutes the entire agreement between you and BLINDSIDEBETS with respect to the Web Site and supersedes all prior or contemporaneous communications and proposals (whether oral, written, or electronic) between you and BLINDSIDEBETS with respect to the Web Site. If any part of these Terms is held invalid or unenforceable, that portion shall be construed in a manner consistent with applicable law to reflect, as nearly as possible, the original intentions of the parties and the remaining portion shall remain in full force and effect. </p>

                                <h3 class="mt-5">Changes to the Terms</h3>
                                <p class="mt-5">We may periodically modify and supplement these Terms and the notice provided to you will be the updating of these Terms. You are responsible for regularly checking these Terms for revisions. All amended Terms become effective upon our posting to the Web Site, and any use of the Web Site after such revisions have been posted signifies your consent and agreement to the modified Terms.</p>

                                <p class="mt-5"><b>These Terms of Use were last modified and are effective as of June 13, 2022.</b></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
